### ISSUE TITLE
getting errors when adding the source to netbeans

### ISSUE THREAD

**Issue by MrrCrazy** [Maxcloud/Mushy#30]
warning: [options] bootstrap class path not set in conjunction with -source 1.7
C:\Users\name\Desktop\Mushys\src\client\SkillFactory.java:76: error: lambda expressions are not supported in -source 1.7
        data.getData("FamiliarSkill.img").forEach(img -> addFamiliarData(img));
  (use -source 8 or higher to enable lambda expressions)
C:\Users\name\Desktop\Mushys\src\server\quest\MapleQuestAction.java:167: error: lambda expressions are not supported in -source 1.7
            boolean found = code.stream().anyMatch(codec-> codec / 100 == c.getJob() /  100);
  (use -source 8 or higher to enable lambda expressions)
C:\Users\name\Desktop\Mushys\src\server\quest\MapleQuestRequirement.java:257: error: lambda expressions are not supported in -source 1.7
            Predicate<MaplePet> pet = p-> p.getSummoned() &&
                                       ^
  (use -source 8 or higher to enable lambda expressions)
3 errors
1 warning
C:\Users\name\Documents\NetBeansProjects\Mushys\nbproject\build-impl.xml:942: The following error occurred while executing this line:
C:\Users\name\Documents\NetBeansProjects\Mushys\nbproject\build-impl.xml:287: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 1 second)

**Comment by Zenns** [comment]
Update to JDK 8.

**Comment by MrrCrazy** [comment]
worked now i have bat error 
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
Press any key to continue . . .

**Comment by Maxcloud** [comment]
You need to install JRE 8.
