### ISSUE TITLE
error code 38

### ISSUE THREAD

**Issue by MrrCrazy** [Maxcloud/Mushy#33]
[Error 38](INTRO_ENABLE_UI) Data: Data: 01 01 00

**Comment by AlanMorel** [comment]
We're going to need more information than that. At the very least what you did to cause that would help. We have yet to add proper error handling.

**Comment by Zenns** [comment]
Hi, may I know which map you were on when it error 38, I believe it was cause by Intro_Enable_Ui correct me if I am wrong.

**Comment by AlanMorel** [comment]
Fixed by Zenns.
