### ISSUE TITLE
Error code 38:

### ISSUE THREAD

**Issue by ghost** [Maxcloud/Mushy#36]
Two people can not be in the same map, causes error code 38, instant disconnection.

**Comment by Zenns** [comment]
Hi, may we know the opcode that is error code it show on the console.

**Comment by ghost** [comment]
I can get it for you later hopefully, the server is offline and I have it set up on a friend's pc and it's turned off.

**Comment by AlanMorel** [comment]
This is obviously SPMO, it's not updated yet. You're just going to have to wait until somebody updates it.
